ports:
  - name: http
    containerPort: 8080
    protocol: TCP

livenessProbe:
  httpGet:
    path: /home
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /home
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5